version: '3.5'

services:
  bot:
    container_name: bot
    build: /bot
    env_file:
      - .env

  db:
    build: /db
    container_name: database
    ports:
    - "5433:5432"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes: 
  data:



